### iteration

- do not use range, len, shape[] etc...:)
- for e in tensor_3D:  ... enough



In [12]:
import numpy as np

In [13]:
tensor_3D = np.array([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])  # count [[[ brackets

for e in tensor_3D:
    print(e, "\n")

# do not use range()!
# for i in range(tensor_3D.shape[0]):
#     print(f"Slice {i}:\n", tensor_3D[i], "\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]
 [11 12]] 

