### iteration

- do not use range, len, shape[] etc...:)
- for e in tensor_3D:  ... enough



In [2]:
import numpy as np

In [3]:
tensor_3D = np.array([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])  # count [[[ brackets

for e in tensor_3D:
    print(e, "\n")

# do not use range()!
# for i in range(tensor_3D.shape[0]):
#     print(f"Slice {i}:\n", tensor_3D[i], "\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]
 [11 12]] 



In [ ]:
#nditer
# all elements in a single loop

for e in np.nditer(tensor_3D):
    print(e)

# different step sizes is also possible
# for e in np.nditer(tensor_3D[:, ::2, ::2]):
#     print(e)


# for e in np.nditer(tensor_3D, flags=['external_loop'], order='F'):
#     print(e)
# [1 5 9]
# [ 3  7 11]
# [ 2  6 10]
# [ 4  8 12]

# nested loops
# for x in tensor_3D:
#     for y in x:
#         for z in y:
#             print(z)

1
2
3
4
5
6
7
8
9
10
11
12
