### numpy

2 critical things:
- dimension: count the brackets **[[[** = tensor, 3D
- understand what it is: _scalar, vector, or tensor_
- accessing: two different way to access [, , ,] or [][][]  (w/ some differences)
- shape:  esp. after slicing!
    - shape depends on _scalar, vector, or tensor_

numpy array is a scalar, vector or tensor. general term. dimension defines what it is. 
So think of it as
```
-           scalar (no-dim)   |  vector (=1D)            |   tensors (2D, 3D... matrices)
- shape      (none)               (n, none)                   (n, m, k, ..)
- sliced     ..... consider sliced dimension ...  scalar, vector or tensor ?

- after slicing shape             [i] valid -> scalar  = (none)
                                  [:] valid -> vector  = (n, none)
                                  [:] valid -> tensor  = (n, m, k, ..)   
```


In [ ]:
import numpy as np


In [6]:
scalar = np.array(42)

# scalar[0] # not valid
scalar, scalar.shape


(array(42), ())

In [ ]:
vector_1D = np.array([1, 2, 3, 9, 16]) #misleading syntax :) it has rows ! so it is vector

#vector_1D[] not valid
#row

print(vector_1D, vector_1D.shape)
print(vector_1D[:], vector_1D[:].shape)      # -> still 1D = vector
print(vector_1D[:2], vector_1D[:2].shape)    # -> still 1D = vector
print(vector_1D[0], vector_1D[0].shape)      # -> scalar

[ 1  2  3  9 16] (5,)
[ 1  2  3  9 16] (5,)
[1 2] (2,)
1 ()


In [ ]:
tensor_2D = np.array([[1, 2, 3, 5], 
                      [4, 5, 6, 6], 
                      [7, 8, 9, 33]])  # count [[ brackets

#tensor_2D[,] not valid
#row, column

print(tensor_2D[:, :], tensor_2D[:, :].shape)    # -> still 2D
print(tensor_2D[0][2], tensor_2D[0][2].shape)    # -> scalar
print(tensor_2D[1], tensor_2D[1].shape)          # -> vector 1D

[[ 1  2  3  5]
 [ 4  5  6  6]
 [ 7  8  9 33]] (3, 4)
3 ()
[4 5 6 6] (4,)


In [ ]:
tensor_3D = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[7, 8, 9], [10, 11, 12]], 
                     [[13, 14, 15], [16, 17, 18]]])

#tensor_3D[,,] not valid
#matrix
#row, column, depth ...    

print(tensor_3D[:, :, :], tensor_3D[:, :, :].shape) # -> still 3D
print(tensor_3D[0][1][2], tensor_3D[0][1][2].shape) # -> scalar
print(tensor_3D[0], tensor_3D[0].shape)             # -> matrix 2D
print(tensor_3D[0,0], tensor_3D[0,0].shape)         # -> vector 1D

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]] (3, 2, 3)
6 ()
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3] (3,)
