### join

- join by axis 
````
  / depth axis=2
 /
|------ axis=1 column
|
| axis=0 row


concatenate
stack

````


In [2]:
import numpy as np

In [3]:
# vector 1d

vector_a = np.array([1, 2, 3]) # vector, shape (3,), 1D
vector_b = np.array([4, 5, 6])

concatenated_vector = np.concatenate((vector_a, vector_b)) #axis=0 default
print(f"Concatenated Vector: {concatenated_vector} - Shape: {concatenated_vector.shape}")

Concatenated Vector: [1 2 3 4 5 6] - Shape: (6,)


In [4]:
# tensor 2d
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
matrix_b = np.array([[7, 8, 9], [10, 11, 12]])  # shape (2, 3)

concatenated_vector_2d_row = np.concatenate((matrix_a, matrix_b), axis=0)  # shape (4, 3)
concatenated_vector_2d_col = np.concatenate((matrix_a, matrix_b), axis=1)  # shape (2, 6)

print(f"Concatenated 2D Matrix along rows (axis=0):\n{concatenated_vector_2d_row}\nShape: {concatenated_vector_2d_row.shape}")
print(f"Concatenated 2D Matrix along columns (axis=1):\n{concatenated_vector_2d_col}\nShape: {concatenated_vector_2d_col.shape}")


Concatenated 2D Matrix along rows (axis=0):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Concatenated 2D Matrix along columns (axis=1):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Shape: (2, 6)


In [5]:
#tensor 3d
tensor_a = np.array([[[1, 2], [3, 4]], 
                     [[5, 6], [7, 8]]])  # shape (2, 2, 2)
tensor_b = np.array([[[9, 10], [11, 12]],
                     [[13, 14], [15, 16]]])  # shape (2, 2, 2)

concatenated_tensor_depth = np.concatenate((tensor_a, tensor_b), axis=2)  # shape (2, 2, 4)
concatenated_vector_3d_row = np.concatenate((tensor_a, tensor_b), axis=0)  # shape (4, 2, 2)
concatenated_vector_3d_col = np.concatenate((tensor_a, tensor_b), axis=1)  # shape (2, 4, 2)

print(f"Concatenated 3D Tensor along depth (axis=2):\n{concatenated_tensor_depth}\nShape: {concatenated_tensor_depth.shape}")
print(f"Concatenated 3D Tensor along rows (axis=0):\n{concatenated_vector_3d_row}\nShape: {concatenated_vector_3d_row.shape}")
print(f"Concatenated 3D Tensor along columns (axis=1):\n{concatenated_vector_3d_col}\nShape: {concatenated_vector_3d_col.shape}")


Concatenated 3D Tensor along depth (axis=2):
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]
Shape: (2, 2, 4)
Concatenated 3D Tensor along rows (axis=0):
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
Shape: (4, 2, 2)
Concatenated 3D Tensor along columns (axis=1):
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
Shape: (2, 4, 2)
