### numpy

- two differeent way to access [, , ,], or [][][] 
- with some caution
- the other critical thing is shape after slicing !!!

In [ ]:
import numpy as np


array([1, 2, 3])

In [12]:
oneD = np.array([1, 2, 3])

#oneD[] not valid

oneD[:], oneD

(array([1, 2, 3]), array([1, 2, 3]))

In [19]:
twoD = np.array([[1, 2, 3, 5], [4, 5, 6, 6], [7, 8, 9, 33]])

#twoD[,] not valid
#row, column

twoD[:, :], twoD[:, :].shape, \
twoD[0][2], twoD[0][2].shape, \
twoD[1], twoD[1].shape

(array([[ 1,  2,  3,  5],
        [ 4,  5,  6,  6],
        [ 7,  8,  9, 33]]),
 (3, 4),
 np.int64(3),
 (),
 array([4, 5, 6, 6]),
 (4,))