### reshaping, flatting

- -1 means, it calculates dimension for you

In [2]:
import numpy as np

In [ ]:
#reshape 1d->2d, 3d , dimention increased
vector_1D = np.array([1, 2, 3, 9, 16, 25, 36, 49, 64, 81, 100, 121])  

vector_1D.size # number of elements in the array

tensor_3D = vector_1D.reshape(2, 2, 3) 
tensor_2D = vector_1D.reshape(3, -1)

print(tensor_3D)
print(tensor_2D)  # == print(vector_1D.reshape(3, 4))

#flatten tensor_3D -> vector_1D
flat_vector = tensor_3D.flatten()  # == tensor_3D.reshape(-1)

print(flat_vector)


[[[  1   2   3]
  [  9  16  25]]

 [[ 36  49  64]
  [ 81 100 121]]]
[[  1   2   3   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[  1   2   3   9  16  25  36  49  64  81 100 121]
