## numpy - random generators

In [1]:
#random generator example
# use generators not np.random!
import numpy.random as random


random_ints = random.default_rng(seed=42).integers(low=0, high=100, size=10)  #array([ 8, 56, 92, 14, 82,  4, 90, 45, 66, 39])
random_ints_2D = random.default_rng(seed=42).integers(low=0, high=100, size=(2,4))  #array([[12, 52, 93, 15],
                                                                #   [72, 61, 21, 83]])  
# count brackets [[......]] = 2d

random_ints_3D = random.default_rng(seed=42).integers(low=0, high=100, size=(2,3,4)) 

random_ints, random_ints_2D, random_ints_3D


(array([ 8, 77, 65, 43, 43, 85,  8, 69, 20,  9]),
 array([[ 8, 77, 65, 43],
        [43, 85,  8, 69]]),
 array([[[ 8, 77, 65, 43],
         [43, 85,  8, 69],
         [20,  9, 52, 97]],
 
        [[73, 76, 71, 78],
         [51, 12, 83, 45],
         [50, 37, 18, 92]]]))

In [2]:
# 1d = []
# 2d = [][]
random_ints[0], \
random_ints_2D[0][0] #2d = [][]

(np.int64(8), np.int64(8))

In [3]:
# 3d = [[[ .... ]]]

random_ints_3D[0] #2d, 3x4 matrix

array([[ 8, 77, 65, 43],
       [43, 85,  8, 69],
       [20,  9, 52, 97]])