### graph

In [ ]:
import scipy.sparse.csgraph as spg
import scipy.sparse as sp
import numpy as np

# create a sparse adjacency matrix
# 0 indicates no edge, positive values indicate edges (with weights, if any)
# n = elements (4x4 = 16)
                         #    A  B  C  D
adjacency_matrix = np.array([[0, 1, 0, 0],    # A
                             [1, 0, 1, 1],    # B
                             [0, 1, 0, 0],    # C
                             [0, 1, 0, 0]])   # D

adjacency_matrix

array([[0, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])

In [2]:
#adjacency matrix to sparse matrix
adjacency_sparse_matrix = sp.csr_matrix(adjacency_matrix)

print(adjacency_sparse_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (4, 4)>
  Coords	Values
  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (1, 3)	1
  (2, 1)	1
  (3, 1)	1


In [3]:
#connected components = clusters in the graph
#
n_components, labels = spg.connected_components(adjacency_sparse_matrix)
n_components, labels

(1, array([0, 0, 0, 0], dtype=int32))

In [4]:
#shortest path with dijkstra
dist_matrix, predecessors = spg.dijkstra(adjacency_sparse_matrix, return_predecessors=True, unweighted=True)
dist_matrix, predecessors

(array([[0., 1., 2., 2.],
        [1., 0., 1., 1.],
        [2., 1., 0., 2.],
        [2., 1., 2., 0.]]),
 array([[-9999,     0,     1,     1],
        [    1, -9999,     1,     1],
        [    1,     2, -9999,     1],
        [    1,     3,     1, -9999]], dtype=int32))

In [6]:
#shortest path wth floyd-warshall
dist_matrix_fw, predecessors_fw = spg.floyd_warshall(adjacency_sparse_matrix, return_predecessors=True, unweighted=True)
dist_matrix_fw
  

array([[0., 1., 2., 2.],
       [1., 0., 1., 1.],
       [2., 1., 0., 2.],
       [2., 1., 2., 0.]])

#### depth first order

In [10]:
# depth first order
dfs_order = spg.depth_first_order(adjacency_sparse_matrix, 0, directed=False, return_predecessors=False)
dfs_order


array([0, 1, 2, 3], dtype=int32)