### spatial

In [20]:
import scipy.spatial as spatial
import numpy as np

points = np.array([[2, 4], 
                   [3, 4], 
                   [3, 0], 
                   [2, 2],
                   [4, 1]])

In [21]:
# triangulation of the points
simplex = spatial.Delaunay(points)
print(f"Delaunay simplices (triangles):\n {simplex.simplices}")


Delaunay simplices (triangles):
 [[3 2 4]
 [3 1 0]
 [1 3 4]]


In [22]:
#convex hull of the points (smallest polygon enclosing all points)
hull = spatial.ConvexHull(points)

print(f"Convex hull vertices:\n {hull.vertices}")
print(f"Convex hull simplices:\n {hull.simplices}")

Convex hull vertices:
 [2 4 1 0 3]
Convex hull simplices:
 [[2 4]
 [1 0]
 [1 4]
 [3 0]
 [3 2]]


In [23]:
#kd-tree for nearest neighbor search
kdtree = spatial.KDTree(points)

query_point = np.array([3, 2])
distance, index = kdtree.query(query_point)

print(f"Nearest neighbor to {query_point} is point {points[index]} at distance {distance}")

Nearest neighbor to [3 2] is point [2 2] at distance 1.0


#### distances
- euclidian
- manhatten
- cosine


In [ ]:
#euclidian distances = straight line distance
distances = spatial.distance.pdist(points, metric='euclidean')

#distance matrix
distance_matrix = spatial.distance.squareform(distances)     


distances, distance_matrix

(array([1.        , 4.12310563, 2.        , 3.60555128, 4.        ,
        2.23606798, 3.16227766, 2.23606798, 1.41421356, 2.23606798]),
 array([[0.        , 1.        , 4.12310563, 2.        , 3.60555128],
        [1.        , 0.        , 4.        , 2.23606798, 3.16227766],
        [4.12310563, 4.        , 0.        , 2.23606798, 1.41421356],
        [2.        , 2.23606798, 2.23606798, 0.        , 2.23606798],
        [3.60555128, 3.16227766, 1.41421356, 2.23606798, 0.        ]]))

In [ ]:
#manhatten distances = sum of absolute differences
manhatten_distances = spatial.distance.pdist(points, metric='cityblock') 

#manhatten distance matrix
manhatten_distance_matrix = spatial.distance.squareform(manhatten_distances)    

manhatten_distance_matrix

array([[0., 1., 5., 2., 5.],
       [1., 0., 4., 3., 4.],
       [5., 4., 0., 3., 2.],
       [2., 3., 3., 0., 3.],
       [5., 4., 2., 3., 0.]])

In [ ]:
#cosine distances = angle between vectors
cosine_distances = spatial.distance.pdist(points, metric='cosine')  

#cosine distance matrix
cosine_distance_matrix = spatial.distance.squareform(cosine_distances)

cosine_distance_matrix

array([[0.        , 0.01613009, 0.5527864 , 0.0513167 , 0.34920863],
       [0.01613009, 0.        , 0.4       , 0.01005051, 0.223886  ],
       [0.5527864 , 0.4       , 0.        , 0.29289322, 0.0298575 ],
       [0.0513167 , 0.01005051, 0.29289322, 0.        , 0.14250707],
       [0.34920863, 0.223886  , 0.0298575 , 0.14250707, 0.        ]])