### sparse

In [6]:
import scipy.sparse as sp
import numpy as np

sparse2D = np.array([[0, 0, 1], [1, 0, 0], [0, 0, 2]])
print(sparse2D) #3x3 [][]

#csrow - based
matrix = sp.csr_matrix(sparse2D)
print(matrix)    # (row=0, column=2)	-> 1

[[0 0 1]
 [1 0 0]
 [0 0 2]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	1
  (1, 0)	1
  (2, 2)	2


In [7]:
#values
matrix.data    # array([1, 1, 2])

array([1, 1, 2])

In [23]:
matrix.count_nonzero  # 3 out of 9 elements

<bound method _cs_matrix.count_nonzero of <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>>

In [21]:
matrix_csc = matrix.tocsc()

print(matrix_csc) 

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (1, 0)	1
  (0, 2)	1
  (2, 2)	2
