Test chi-square test for 2 rolling dices and understand the trick.


In [50]:
from numpy import random
import numpy
from scipy import stats


In [132]:
# roll 6 times
expectedDice = random.randint(1, 7, size=(6,200))
expectedDice


array([[6, 6, 4, ..., 1, 1, 6],
       [3, 2, 5, ..., 2, 5, 1],
       [3, 1, 1, ..., 3, 3, 6],
       [2, 3, 6, ..., 6, 1, 2],
       [4, 3, 2, ..., 1, 6, 4],
       [2, 4, 3, ..., 1, 5, 3]])

In [125]:
opponentDice = random.randint(5, 7, size=(6,20))
opponentDice


array([[5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 6, 5],
       [6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 6],
       [6, 5, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5, 6, 5, 5, 5],
       [6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5],
       [5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 5],
       [5, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 6, 5, 6, 5, 6]])

In [128]:
# calculate occurrence
indexOfExpectedDice, occurrenceOfExpectedDice = numpy.unique(expectedDice, return_counts=True)
occurrenceOfExpectedDice


array([205, 220, 189, 202, 202, 182])

In [129]:
# calculate occurrence
indexOfOpponentDice, occurrenceOfOpponentDice = numpy.unique(opponentDice, return_counts=True)
occurrenceOfOpponentDice


array([65, 55])

In [130]:
# test w/ chi-square test
# use below if you dont know expected
#chi2_stat, pvalue, dof, ex = stats.chi2_contingency(opponentDice, expectedDice)

# use below if you know the expected
stats.chi2_contingency(opponentDice, expectedDice)

(4.706453431613377,
 1.0,
 95,
 array([[5.54198473, 5.3740458 , 5.3740458 , 5.54198473, 5.70992366,
         5.70992366, 5.54198473, 5.20610687, 5.3740458 , 5.3740458 ,
         5.3740458 , 5.3740458 , 5.54198473, 5.70992366, 5.8778626 ,
         5.54198473, 5.54198473, 5.20610687, 5.70992366, 5.3740458 ],
        [5.54198473, 5.3740458 , 5.3740458 , 5.54198473, 5.70992366,
         5.70992366, 5.54198473, 5.20610687, 5.3740458 , 5.3740458 ,
         5.3740458 , 5.3740458 , 5.54198473, 5.70992366, 5.8778626 ,
         5.54198473, 5.54198473, 5.20610687, 5.70992366, 5.3740458 ],
        [5.54198473, 5.3740458 , 5.3740458 , 5.54198473, 5.70992366,
         5.70992366, 5.54198473, 5.20610687, 5.3740458 , 5.3740458 ,
         5.3740458 , 5.3740458 , 5.54198473, 5.70992366, 5.8778626 ,
         5.54198473, 5.54198473, 5.20610687, 5.70992366, 5.3740458 ],
        [5.44122137, 5.27633588, 5.27633588, 5.44122137, 5.60610687,
         5.60610687, 5.44122137, 5.11145038, 5.27633588, 5.27633588,


In [131]:
## evaluate the results
if pvalue > 0.05:
    print("dice is tricky, pvalue=" + str(pvalue))
    print("%{} chance to see opponentDice results :)".format(pvalue))
else:
    print("dice is fair, pvalue=" + str(pvalue))



dice is tricky, pvalue=1.0
%1.0 chance to see opponentDice results :)
