Test chi-square test for 2 rolling dices and understand the trick.


In [8]:
from numpy import random
import numpy 


In [20]:
normalDice = random.randint(1, 7, size=20)
normalDice


array([1, 1, 5, 2, 2, 5, 6, 1, 4, 2, 3, 1, 6, 3, 4, 4, 4, 2, 3, 1])

In [22]:
opponentDice = random.randint(5, 7, size=20)
opponentDice


array([5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6])

In [23]:
# calculate occurrence
indexOfNormalDice, occurrenceOfNormalDice = numpy.unique(normalDice, return_counts=True)
occurrenceOfNormalDice


array([5, 4, 3, 4, 2, 2])

In [25]:
# calculate occurrence
indexOfOpponentDice, occurrenceOfOpponentDice = numpy.unique(opponentDice, return_counts=True)
occurrenceOfOpponentDice


array([ 7, 13])

In [ ]:
# test w/ chi-square test


In [ ]:
# evaluate the results