Test chi-square test for 2 rolling dices and understand the trick.


In [202]:
from numpy import random
import numpy
from scipy import stats


In [237]:
# roll 6 times
expectedDice = random.randint(1, 7, size=(6,200))
expectedDice


array([[6, 6, 6, ..., 3, 1, 2],
       [6, 6, 5, ..., 1, 1, 3],
       [6, 6, 4, ..., 3, 1, 1],
       [4, 6, 5, ..., 6, 4, 3],
       [2, 2, 5, ..., 1, 5, 4],
       [5, 4, 1, ..., 2, 4, 3]])

In [238]:
opponentDice = random.randint(5, 7, size=(6,200))
opponentDice


array([[5, 5, 6, ..., 5, 6, 6],
       [5, 6, 6, ..., 5, 6, 5],
       [6, 6, 5, ..., 6, 6, 5],
       [6, 5, 5, ..., 6, 6, 6],
       [6, 5, 5, ..., 5, 6, 5],
       [5, 6, 5, ..., 6, 6, 6]])

In [239]:
# calculate occurrence
indexOfExpectedDice, occurrenceOfExpectedDice = numpy.unique(expectedDice, return_counts=True)
occurrenceOfExpectedDice


array([196, 208, 181, 210, 181, 224])

In [250]:
# calculate occurrence
indexOfOpponentDice, occurrenceOfOpponentDice = numpy.unique(opponentDice, return_counts=True)

occurrenceOfOpponentDice = numpy.concatenate((numpy.array([0,0,0,0]),
                                               occurrenceOfOpponentDice))
occurrenceOfOpponentDice

array([  0,   0,   0,   0, 617, 583])

In [252]:
# test w/ chi-square test
# use below if you dont know expected
# chi2_stat, pvalue, dof, ex = stats.chi2_contingency(occurrenceOfOpponentDice)

# use below if you know the expected
statistic, pvalue = stats.chisquare(occurrenceOfOpponentDice, 
                                    occurrenceOfExpectedDice)

pvalue


0.0