Test chi-square test for 2 rolling dices and understand the trick.


In [50]:
from numpy import random
import numpy
from scipy import stats


In [51]:
expectedDice = random.randint(1, 7, size=20)
expectedDice


array([3, 1, 4, 6, 1, 5, 2, 2, 2, 6, 5, 4, 6, 4, 1, 6, 4, 6, 1, 6])

In [52]:
opponentDice = random.randint(5, 7, size=20)
opponentDice


array([5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5])

In [53]:
# calculate occurrence
indexOfExpectedDice, occurrenceOfExpectedDice = numpy.unique(expectedDice, return_counts=True)
occurrenceOfExpectedDice


array([4, 3, 1, 4, 2, 6])

In [54]:
# calculate occurrence
indexOfOpponentDice, occurrenceOfOpponentDice = numpy.unique(opponentDice, return_counts=True)
occurrenceOfOpponentDice


array([ 9, 11])

In [55]:
# test w/ chi-square test
statistic, pvalue = stats.chisquare(opponentDice, expectedDice )


In [56]:
## evaluate the results
if pvalue < 0.5:
    print("dice is tricky")
else:
    print("dice is fair")



dice is tricky
