In [6]:
#enable matplotlib backend
%matplotlib


Using matplotlib backend: Qt5Agg


In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
np.random.seed(1000) # same numbers will generate

N = 20
x = np.random.rand(N)
y = np.random.rand(N)

colours = np.random.rand(N)
area = (30 * np.random.rand(N)) ** 2

x, y, colours, area

(array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
        0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072,
        0.20708234, 0.74246953, 0.39215413, 0.18225652, 0.74353941,
        0.06958208, 0.8853372 , 0.9526444 , 0.93114343, 0.41543095]),
 array([0.02898166, 0.98202748, 0.33963768, 0.70668719, 0.36187707,
        0.0351059 , 0.85505825, 0.65725351, 0.76568299, 0.55408724,
        0.88509294, 0.90419762, 0.0104217 , 0.07455674, 0.24462921,
        0.13330475, 0.6979251 , 0.39820488, 0.88312219, 0.18100751]),
 array([0.43249917, 0.0181432 , 0.69143786, 0.46969065, 0.12822219,
        0.89133705, 0.91820362, 0.07312099, 0.04544794, 0.4385729 ,
        0.60172093, 0.31022703, 0.68190824, 0.20901315, 0.5196043 ,
        0.56598883, 0.44116739, 0.13755616, 0.21354319, 0.13337189]),
 array([ 93.48764742,  49.23286438, 250.42887414, 288.29102057,
        172.8372602 ,  93.24178752, 281.87805329, 673.94067739,
        646.09944686,  10.46208715,  90.05221435, 

In [10]:
plt.scatter(x, y, s=area, c=colours, alpha=0.5)

plt.show()