Test chi-square test for 2 rolling dices and understand the trick.


In [202]:
from numpy import random
import numpy
from scipy import stats


In [265]:
# roll 6 times
expectedDice = random.randint(1, 7, size=(6,20000))
expectedDice


array([[6, 2, 4, ..., 3, 6, 1],
       [5, 6, 5, ..., 3, 6, 2],
       [3, 6, 1, ..., 5, 1, 2],
       [4, 4, 2, ..., 1, 4, 3],
       [2, 5, 3, ..., 3, 3, 3],
       [1, 5, 3, ..., 6, 5, 6]])

In [266]:
opponentDice = random.randint(5, 7, size=(6,2000))
opponentDice


array([[6, 5, 5, ..., 6, 6, 6],
       [6, 6, 5, ..., 6, 5, 6],
       [6, 5, 6, ..., 5, 5, 5],
       [5, 6, 5, ..., 5, 6, 5],
       [5, 5, 6, ..., 6, 6, 6],
       [5, 5, 6, ..., 6, 6, 5]])

In [267]:
# calculate occurrence
indexOfExpectedDice, occurrenceOfExpectedDice = numpy.unique(expectedDice, return_counts=True)
occurrenceOfExpectedDice


array([20106, 20042, 20067, 20127, 19739, 19919])

In [268]:
# calculate occurrence
indexOfOpponentDice, occurrenceOfOpponentDice = numpy.unique(opponentDice, return_counts=True)

occurrenceOfOpponentDice = numpy.concatenate((numpy.array([0,0,0,0]),
                                               occurrenceOfOpponentDice))
occurrenceOfOpponentDice

array([   0,    0,    0,    0, 6104, 5896])

In [269]:
# test w/ chi-square test
# use below if you dont know expected
# chi2_stat, pvalue, dof, ex = stats.chi2_contingency(occurrenceOfOpponentDice)

# use below if you know the expected
statistic, pvalue = stats.chisquare(occurrenceOfOpponentDice, 
                                    occurrenceOfExpectedDice)

pvalue


0.0